# -*- coding: utf-8 -*-
"""Med-Insurance Calc_ML

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lN9XUqogpQdu58CHD1XWDKpBMn2PQZEY

Importing the dependencies"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.preprocessing import StandardScaler
from sklearn import metrics
try:
    import xgboost as xgb
    XGBOOST_AVAILABLE = True
except ImportError:
    XGBOOST_AVAILABLE = False
    print("XGBoost not installed. Install with: pip install xgboost")
import warnings
warnings.filterwarnings('ignore')

"""Data collection and analysis"""

#first we will load the data from csv file to a pandas dataframe
insurance_dataset = pd.read_csv('Medicalpremium.csv')

#trying to print 1st 5 rows of the data frame
insurance_dataset.head()

#goint to find the no of rows and coloumns
insurance_dataset.shape

# to get some info about the data set
insurance_dataset.info()

"""6 coulumns are features and charges column is called target"""

#checking for any missing mvalues
insurance_dataset.isnull().sum()

#Data analysis
#statistical measures of data set
insurance_dataset.describe()

# Finding the distribution of age value (commented out)
# sns.set()
# plt.figure(figsize=(8,8))
# sns.distplot(insurance_dataset['age'])
# plt.title('Age distribution')
# plt.show()

# Gender column (commented out)
# plt.figure(figsize=(8,8))
# sns.countplot(x='sex', data=insurance_dataset)
# plt.title('Gender distribution')
# plt.show()

# Diabetes column analysis
insurance_dataset['Diabetes'].value_counts()

# Blood Pressure Problems column
insurance_dataset['BloodPressureProblems'].value_counts()

# Chronic Diseases column
insurance_dataset['AnyChronicDiseases'].value_counts()

# Known Allergies column
insurance_dataset['KnownAllergies'].value_counts()

# Charges Distribution (commented out)
# plt.figure(figsize=(8,8))
# sns.distplot(insurance_dataset['charges'])
# plt.title('Charges distribution')
# plt.show()

"""#Data Processing

Encoding the categorical features """

# Data preprocessing
# All columns are already numeric (0/1 for binary features)
# No encoding needed for this dataset

"""Splitting the features and targets"""

# Select all features except the target (PremiumPrice)
X = insurance_dataset.drop(columns='PremiumPrice', axis=1)
Y = insurance_dataset['PremiumPrice']
print(X)
print(Y)

"""Spliting the data into training data & testing data"""

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state = 2)
print(X.shape, X_train.shape, X_test.shape)

"""Model Training:
Trying Multiple Models to Find the Best One
"""

# Initialize models
models = {
    'Linear Regression': LinearRegression(),
    'Ridge Regression': Ridge(alpha=10.0),
    'Random Forest': RandomForestRegressor(n_estimators=200, random_state=2, max_depth=20, min_samples_split=5),
    'Gradient Boosting': GradientBoostingRegressor(n_estimators=200, random_state=2, max_depth=7, learning_rate=0.05)
}

# Add XGBoost if available
if XGBOOST_AVAILABLE:
    models['XGBoost'] = xgb.XGBRegressor(
        n_estimators=200,
        max_depth=7,
        learning_rate=0.05,
        random_state=2,
        objective='reg:squarederror'
    )

best_model = None
best_score = 0
best_model_name = ""

print("\n" + "="*60)
print("Model Comparison")
print("="*60)

# Train and evaluate each model
for name, model in models.items():
    # Train the model
    model.fit(X_train, Y_train)
    
    # Make predictions
    train_pred = model.predict(X_train)
    test_pred = model.predict(X_test)
    
    # Calculate R² scores
    r2_train = metrics.r2_score(Y_train, train_pred)
    r2_test = metrics.r2_score(Y_test, test_pred)
    
    # Calculate MAE (Mean Absolute Error)
    mae_test = metrics.mean_absolute_error(Y_test, test_pred)
    
    print(f"\n{name}:")
    print(f"  Training R² score: {r2_train:.4f}")
    print(f"  Test R² score: {r2_test:.4f}")
    print(f"  Mean Absolute Error: INR {mae_test:.2f}")
    
    # Keep track of the best model
    if r2_test > best_score:
        best_score = r2_test
        best_model = model
        best_model_name = name

print("\n" + "="*60)
print(f"Best Model: {best_model_name} with R² score: {best_score:.4f}")
print("="*60)

# Use the best model as the final regressor
regressor = best_model

"""Model Evaluation"""

# prediction on training data
training_data_prediction = regressor.predict(X_train)

# R squared value
r2_train = metrics.r2_score(Y_train, training_data_prediction)
print('\nFinal Model Training R² score:', r2_train)

# prediction on test data
test_data_prediction = regressor.predict(X_test)

# R squared value
r2_test = metrics.r2_score(Y_test, test_data_prediction)
print('Final Model Test R² score:', r2_test)

"""Building a Predictive System"""

# Example input: Age, Diabetes, BloodPressureProblems, AnyTransplants, AnyChronicDiseases, Height, Weight, KnownAllergies, HistoryOfCancerInFamily, NumberOfMajorSurgeries
# Using data from first row: Age=45, Diabetes=0, BloodPressure=0, Transplants=0, ChronicDiseases=0, Height=155, Weight=57, Allergies=0, CancerHistory=0, Surgeries=0
input_data = (45, 0, 0, 0, 0, 155, 57, 0, 0, 0)

# changing input_data to a numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the array
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = regressor.predict(input_data_reshaped)
print(prediction)

print('The insurance cost is INR ', prediction[0])